[package]
name = "mouse_lang_interpreter"
version = "0.1.0"
authors = ["Ergeibi Mohamed <ergeibi.mohamed@gmail.com>"]
edition = "2021"

[dependencies]
miette = "7.2.0"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
